// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2umk_9H5zRxnbZ9K5bCz3eruvEuYWwM',
    appId: '1:922113700110:web:88c3b4de52f17f376d675f',
    messagingSenderId: '922113700110',
    projectId: 'gs-flutter-4ff09',
    authDomain: 'gs-flutter-4ff09.firebaseapp.com',
    storageBucket: 'gs-flutter-4ff09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0Oa1rKR9YBitb1WMmKMaWaSuT4hEREM',
    appId: '1:922113700110:android:8cc43333450c23336d675f',
    messagingSenderId: '922113700110',
    projectId: 'gs-flutter-4ff09',
    storageBucket: 'gs-flutter-4ff09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4b8PxGuVvth6ryMF49bG-p56BpSfiqM',
    appId: '1:922113700110:ios:88b9d65a48d4359a6d675f',
    messagingSenderId: '922113700110',
    projectId: 'gs-flutter-4ff09',
    storageBucket: 'gs-flutter-4ff09.firebasestorage.app',
    iosBundleId: 'com.example.agrospace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4b8PxGuVvth6ryMF49bG-p56BpSfiqM',
    appId: '1:922113700110:ios:88b9d65a48d4359a6d675f',
    messagingSenderId: '922113700110',
    projectId: 'gs-flutter-4ff09',
    storageBucket: 'gs-flutter-4ff09.firebasestorage.app',
    iosBundleId: 'com.example.agrospace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2umk_9H5zRxnbZ9K5bCz3eruvEuYWwM',
    appId: '1:922113700110:web:17bd9bbe85346af46d675f',
    messagingSenderId: '922113700110',
    projectId: 'gs-flutter-4ff09',
    authDomain: 'gs-flutter-4ff09.firebaseapp.com',
    storageBucket: 'gs-flutter-4ff09.firebasestorage.app',
  );
}
